### ISSUE TITLE
Firefox print preview has artifacts

### ISSUE THREAD

**Issue by toncijajic** [OpenSourceOrg/dotOrg#152]
There is a layout issue with the site's print preview when using Firefox, where the browser shows artifacts, most likely using background's clip path.

## Details

- Example: https://opensource.org/meeting-minutes/2024-10-27
- Print Preview: https://d.pr/i/lYvdUc
- Same happens on Firefox on MacOS and on Linux
- Looks like a header/footer clip path is shown in the print preview
- Looks good in Chrome

**Comment by gin0115** [comment]
Need to rejiggle my forks, but this is the current working fix and will get this pushed up asap

```css
@media print {
    body>.wrapper::after {
        content: none !important;
        display: none !important;
        visibility: hidden !important;
    }
}
```
